# Generated by Django 4.1 on 2022-09-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_comentario_no_coment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacion',
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Autorizacion',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Publicaciones',
        ),
    ]
