# Generated by Django 4.1 on 2022-09-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_autorizacion_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.CharField(max_length=100)),
                ('creador', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('publicaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiante')),
            ],
        ),
    ]
