# Generated by Django 4.1 on 2022-09-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_publicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.CharField(max_length=100)),
                ('autorizacion', models.CharField(max_length=100)),
                ('tipo1', models.CharField(choices=[('Pub', 'Publico'), ('Priv', 'Privado'), ('Au', 'Autorizado'), ('NoAu', 'No autorizado')], default='Pub', max_length=4)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('autorizaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publicaciones')),
            ],
        ),
    ]
