# Generated by Django 4.1 on 2022-09-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_publicaciones_comentario_autorizacion_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='creador',
            new_name='nombre',
        ),
    ]
