# Generated by Django 4.1 on 2022-09-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_creador_comentario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='No_art',
            field=models.IntegerField(max_length=100),
        ),
    ]
